build:
    environment:
        php:
            version: 7.0.6

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - bin/*
        - src/Test/*
        - vendor/*

build:
    environment:
        php: '7.0.6'

    tests:
        override:
            -
                command: 'php vendor/bin/phing qa:run'
                    coverage:
                        file: 'code-coverage.xml'
                        format: 'clover'
