build:
    environment:
        php:
            version: 7.0.6

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - bin/*
        - src/Test/*
        - vendor/*

build:
    environment:
        php: '7.0.6'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
