language: php
php:
  - '7.0'

branches:
  only:
    - master
    - develop
    - /^(bugfix|feature)\/.*$/

install:
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - php vendor/bin/phing qa:run
