commands:
  "Miner\\Command\\Core\\SetupCommand":
    - "@miner.core.setup"

  "Miner\\Command\\Auth\\LoginCommand":
    - "@miner.auth.service"

  "Miner\\Command\\User\\CurrentUserCommand":
    - "@miner.auth.service"
