services:
  #
  # Core-Services
  #
  miner.core.event.dispatcher:
    class: "Symfony\\Component\\EventDispatcher\\EventDispatcher"

  miner.core.environment:
    class: "Miner\\Service\\Core\\EnvironmentService"

  miner.core.setup:
    class: "Miner\\Service\\Core\\SetupService"

  miner.core.context:
    class: "Miner\\Service\\Core\\ContextService"
    arguments:
      - "@miner.core.environment"
      - "@miner.auth.service"
      - "@miner.redmine.api"

  miner.core.context.command:
    class: "Miner\\Service\\Core\\CommandContextService"
    arguments:
      - "@miner.core.environment"
      - "@miner.auth.service"

  #
  # Event Listener
  #
  miner.event.listener.command.prerun:
    class: "Miner\\Event\\Command\\CommandPreRunListener"
    arguments:
      - "@miner.core.context.command"

  #
  # Interactive Shell
  #
  miner.core.shell:
    class: "Miner\\Shell\\MinerShell"
    arguments:
      - "@container"

  miner.core.shell.output:
    class: "Psy\\Output\\ShellOutput"

  #
  # Services
  #
  miner.auth.service:
    class: "Miner\\Service\\Auth\\AuthService"
    arguments:
      - "@miner.redmine.api"
      - "@miner.core.environment"
      - "@miner.registry.user"

  #
  # Redmine API
  #
  miner.redmine.api:
    class: "Miner\\Service\\Redmine\\RedmineApi"
    arguments:
      - "@miner.redmine.api.auth"
      - "@miner.redmine.api.user"
      - "@miner.redmine.api.project"
      - "@miner.redmine.api.ticket"

  miner.redmine.api.auth:
    class: "Miner\\Service\\Redmine\\Auth\\RedmineAuthApi"

  miner.redmine.api.user:
    class: "Miner\\Service\\Redmine\\User\\RedmineUserApi"
    arguments:
      - "@miner.factory.user"

  miner.redmine.api.project:
    class: "Miner\\Service\\Redmine\\Project\\RedmineProjectApi"
    arguments:
      - "@miner.factory.project"

  miner.redmine.api.ticket:
    class: "Miner\\Service\\Redmine\\Ticket\\RedmineTicketApi"
    arguments:
      - "@miner.factory.ticket"

  #
  # Factories
  #
  miner.factory.user:
    class: "Miner\\Factory\\UserFactory"

  miner.factory.project:
    class: "Miner\\Factory\\ProjectFactory"

  miner.factory.ticket:
    class: "Miner\\Factory\\TicketFactory"
    arguments:
      - "@miner.factory.user"
      - "@miner.factory.project"

  #
  # Registries
  #
  miner.registry.user:
    class: "Miner\\Registry\\User\\UserRegistry"
    arguments:
      - "@miner.factory.user"

  #
  # Renderer
  #
  miner.renderer.ticket:
    class: "Miner\\Service\\Renderer\\TicketRenderer"

  miner.renderer.ticket.list:
    class: "Miner\\Service\\Renderer\\TicketListRenderer"

  miner.renderer.project:
    class: "Miner\\Service\\Renderer\\ProjectRenderer"
